App Router Changes
TheDarkThief/club_website pull request #2
Opened 2024-04-19 02:02 UTC by uellenberg

This should fix some of the issues with the app router migration.

2024-04-19 06:45 UTC, TheDarkThief commented on style/index.css
> -@layer reset, base, tokens, recipes, utilities;
What was changed here???

2024-04-19 07:00 UTC, TheDarkThief commented on app/(mainSite)/impactathon/page.tsx
I believe we have spoken (I might be miss remembering) about this but it was noted that the Impactathon really is separate from the main site and I have spoken with the event's manager and he said he would prefer it does _not_ have the CSClub's header and footer.

2024-04-19 07:10 UTC, TheDarkThief requested changes
Thank you for fixing the styling issues, adding back the drawer, and reintroducing SEO.

However there are a few areas I believe could be improved upon and shouldn't take much time.
- as stated in a comment the event organizer would appreciate the CSClubs header being removed, and I agree as it really isn't part of the CSClub, I can undo that if you'd like.
- Next.JS has a system to do metadata based on path, it shouldn't be to hard to implement and would save us from having to define title every time, if you can't get this one done that's fine.
- Please provide a standardized Prettier config or a guide because I don't enjoy making sure two lines of the same code are actually the same besides using double quotes or single quotes

2024-04-19 07:27 UTC, TheDarkThief commented on app/(mainSite)/minecraft/PageBody.tsx
This page has had it's styling broken:
![image](https://github.com/TheDarkThief/club_website/assets/116227005/bb6c20cb-6c50-4388-8a7e-602dfd617505)

2024-04-19 07:32 UTC, TheDarkThief commented on panda.config.ts
> +    fadeInFromAboveAnim: {
why?

2024-04-19 07:33 UTC, TheDarkThief commented on panda.config.ts
> +import {
why as well?

2024-04-19 10:40 UTC, uellenberg commented on panda.config.ts
> +import {
This is prettier.

2024-04-19 10:41 UTC, uellenberg commented on panda.config.ts
> +    fadeInFromAboveAnim: {
This is prettier.

2024-04-19 10:42 UTC, uellenberg commented on app/(mainSite)/minecraft/PageBody.tsx
I don't see any broken styling? Should the text be moved down more?

2024-04-19 10:43 UTC, uellenberg commented on style/index.css
> -@layer reset, base, tokens, recipes, utilities;
This is prettier.

2024-04-19 10:50 UTC, uellenberg commented on app/(mainSite)/impactathon/page.tsx
When I talked to Riko about this (for this very reason) he said he had no problem associating the Impactathon with the CS Club. I also haven't heard anything about this. I have no problem with removing the header and footer if that's what he wants - it's for his event, after all - but that was never communicated to me.

2024-04-19 10:56 UTC, uellenberg commented
> Thank you for fixing the styling issues, adding back the drawer, and reintroducing SEO.
> 
> However there are a few areas I believe could be improved upon and shouldn't take much time.
> 
> * as stated in a comment the event organizer would appreciate the CSClubs header being removed, and I agree as it really isn't part of the CSClub, I can undo that if you'd like.
> * Next.JS has a system to do metadata based on path, it shouldn't be to hard to implement and would save us from having to define title every time, if you can't get this one done that's fine.
> * Please provide a standardized Prettier config or a guide because I don't enjoy making sure two lines of the same code are actually the same besides using double quotes or single quotes

I'm not really sure how path-based metadata could work, especially in the case of the "GameDev" page. We could implement something to do it, but I suspect it'd be more complicated than what we already have and would have to deal with edge cases like this anyway. Plus, some pages have extra details (like descriptions or images), so it's nicer to have it all in one spot. I think that the current approach (which requires one or two lines per file) is the simplest approach. 

There is, and always has been configs for prettier and eslint. You can run `prettier --write *` and `eslint --fix .` in order to apply them. It will used the style specified in the configuration automatically. You probably need to configure your editor to run prettier on save. 

I responded to the last point in one of the review comments.

2024-04-20 00:04 UTC, TheDarkThief commented on app/(mainSite)/minecraft/PageBody.tsx
This it is supposed to look like:
![image](https://github.com/TheDarkThief/club_website/assets/116227005/7431a67a-8911-467a-8bb4-5a24107e384a)

2024-04-20 16:43 UTC, TheDarkThief commented
Perfect thank you

2024-04-20 16:43 UTC, merged